name: 自动爬dytt视频入库mysql
on:
  schedule:
    - cron: "0 1/8 * * *"
  workflow_dispatch:
# 🔥 加这一行就消除警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: 访问 Supabase API 保活
        run: |
          curl -I "https://qdayueqodhquefczraii.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYXl1ZXFvZGhxdWVmY3pyYWlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODkyNzI4NiwiZXhwIjoyMDk0NTAzMjg2fQ.b8SJRCXnSaIrd1wDWtAqXvGKCsZDPPwoVYGHYL3diPE"
          echo "Supabase 已成功访问，项目保持活跃！"
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖     
        run: |
          python -m pip install --upgrade pip
          pip install requests pymysql cryptography

      - name: 运行爬虫
        run: python crawler_mysql.py
        env:
          TZ: Asia/Shanghai         
          MYSQL_DB_HOST: ${{ secrets.TIDB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.TIDB_PORT }}
          MYSQL_DB_NAME: ${{ secrets.TIDB_NAME }}
          MYSQL_DB_USER: ${{ secrets.TIDB_USER }}
          MYSQL_DB_PASS: ${{ secrets.TIDB_PASS }}
          BASE_URL: "https://dyttzy5.tv/api.php/provide/vod/from/dyttm3u8/at/json/"
          BASE_TABLE: "vod_dytt"
